//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 09:03:38 PM EEST 
//


package edu.bonn.AMLGolStandardGenerator.aml;

import javax.xml.bind.annotation.XmlRegistry;

import edu.bonn.AMLGolStandardGenerator.aml.AttributeType.RefSemantic;
import edu.bonn.AMLGolStandardGenerator.aml.AttributeValueRequirementType.NominalScaledType;
import edu.bonn.AMLGolStandardGenerator.aml.AttributeValueRequirementType.OrdinalScaledType;
import edu.bonn.AMLGolStandardGenerator.aml.AttributeValueRequirementType.UnknownType;
import edu.bonn.AMLGolStandardGenerator.aml.CAEXBasicObject.Copyright;
import edu.bonn.AMLGolStandardGenerator.aml.CAEXBasicObject.Description;
import edu.bonn.AMLGolStandardGenerator.aml.CAEXBasicObject.Revision;
import edu.bonn.AMLGolStandardGenerator.aml.CAEXBasicObject.Version;
import edu.bonn.AMLGolStandardGenerator.aml.CAEXFile.ExternalReference;
import edu.bonn.AMLGolStandardGenerator.aml.CAEXFile.InstanceHierarchy;
import edu.bonn.AMLGolStandardGenerator.aml.CAEXFile.InterfaceClassLib;
import edu.bonn.AMLGolStandardGenerator.aml.CAEXFile.RoleClassLib;
import edu.bonn.AMLGolStandardGenerator.aml.CAEXFile.SystemUnitClassLib;
import edu.bonn.AMLGolStandardGenerator.aml.InternalElementType.RoleRequirements;
import edu.bonn.AMLGolStandardGenerator.aml.MappingType.AttributeNameMapping;
import edu.bonn.AMLGolStandardGenerator.aml.MappingType.InterfaceNameMapping;
import edu.bonn.AMLGolStandardGenerator.aml.RoleClassType.ExternalInterface;
import edu.bonn.AMLGolStandardGenerator.aml.SystemUnitClassType.InternalLink;
import edu.bonn.AMLGolStandardGenerator.aml.SystemUnitClassType.SupportedRoleClass;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExternalInterface }
     * 
     */
    public ExternalInterface createRoleClassTypeExternalInterface() {
        return new ExternalInterface();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createCAEXBasicObjectVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link ExternalReference }
     * 
     */
    public ExternalReference createCAEXFileExternalReference() {
        return new ExternalReference();
    }

    /**
     * Create an instance of {@link SystemUnitClassType }
     * 
     */
    public SystemUnitClassType createSystemUnitClassType() {
        return new SystemUnitClassType();
    }

    /**
     * Create an instance of {@link InterfaceNameMapping }
     * 
     */
    public InterfaceNameMapping createMappingTypeInterfaceNameMapping() {
        return new InterfaceNameMapping();
    }

    /**
     * Create an instance of {@link InternalLink }
     * 
     */
    public InternalLink createSystemUnitClassTypeInternalLink() {
        return new InternalLink();
    }

    /**
     * Create an instance of {@link CAEXBasicObject }
     * 
     */
    public CAEXBasicObject createCAEXBasicObject() {
        return new CAEXBasicObject();
    }

    /**
     * Create an instance of {@link RoleRequirements }
     * 
     */
    public RoleRequirements createInternalElementTypeRoleRequirements() {
        return new RoleRequirements();
    }

    /**
     * Create an instance of {@link OrdinalScaledType }
     * 
     */
    public OrdinalScaledType createAttributeValueRequirementTypeOrdinalScaledType() {
        return new OrdinalScaledType();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createCAEXBasicObjectDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Revision }
     * 
     */
    public Revision createCAEXBasicObjectRevision() {
        return new Revision();
    }

    /**
     * Create an instance of {@link SupportedRoleClass }
     * 
     */
    public SupportedRoleClass createSystemUnitClassTypeSupportedRoleClass() {
        return new SupportedRoleClass();
    }

    /**
     * Create an instance of {@link MappingType }
     * 
     */
    public MappingType createMappingType() {
        return new MappingType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link CAEXFile }
     * 
     */
    public CAEXFile createCAEXFile() {
        return new CAEXFile();
    }

    /**
     * Create an instance of {@link InterfaceFamilyType }
     * 
     */
    public InterfaceFamilyType createInterfaceFamilyType() {
        return new InterfaceFamilyType();
    }

    /**
     * Create an instance of {@link RefSemantic }
     * 
     */
    public RefSemantic createAttributeTypeRefSemantic() {
        return new RefSemantic();
    }

    /**
     * Create an instance of {@link SystemUnitClassLib }
     * 
     */
    public SystemUnitClassLib createCAEXFileSystemUnitClassLib() {
        return new SystemUnitClassLib();
    }

    /**
     * Create an instance of {@link InternalElementType }
     * 
     */
    public InternalElementType createInternalElementType() {
        return new InternalElementType();
    }

    /**
     * Create an instance of {@link InterfaceClassType }
     * 
     */
    public InterfaceClassType createInterfaceClassType() {
        return new InterfaceClassType();
    }

    /**
     * Create an instance of {@link CAEXObject }
     * 
     */
    public CAEXObject createCAEXObject() {
        return new CAEXObject();
    }

    /**
     * Create an instance of {@link InstanceHierarchy }
     * 
     */
    public InstanceHierarchy createCAEXFileInstanceHierarchy() {
        return new InstanceHierarchy();
    }

    /**
     * Create an instance of {@link AttributeValueRequirementType }
     * 
     */
    public AttributeValueRequirementType createAttributeValueRequirementType() {
        return new AttributeValueRequirementType();
    }

    /**
     * Create an instance of {@link RoleClassType }
     * 
     */
    public RoleClassType createRoleClassType() {
        return new RoleClassType();
    }

    /**
     * Create an instance of {@link RoleFamilyType }
     * 
     */
    public RoleFamilyType createRoleFamilyType() {
        return new RoleFamilyType();
    }

    /**
     * Create an instance of {@link UnknownType }
     * 
     */
    public UnknownType createAttributeValueRequirementTypeUnknownType() {
        return new UnknownType();
    }

    /**
     * Create an instance of {@link RoleClassLib }
     * 
     */
    public RoleClassLib createCAEXFileRoleClassLib() {
        return new RoleClassLib();
    }

    /**
     * Create an instance of {@link AttributeNameMapping }
     * 
     */
    public AttributeNameMapping createMappingTypeAttributeNameMapping() {
        return new AttributeNameMapping();
    }

    /**
     * Create an instance of {@link NominalScaledType }
     * 
     */
    public NominalScaledType createAttributeValueRequirementTypeNominalScaledType() {
        return new NominalScaledType();
    }

    /**
     * Create an instance of {@link SystemUnitFamilyType }
     * 
     */
    public SystemUnitFamilyType createSystemUnitFamilyType() {
        return new SystemUnitFamilyType();
    }

    /**
     * Create an instance of {@link Copyright }
     * 
     */
    public Copyright createCAEXBasicObjectCopyright() {
        return new Copyright();
    }

    /**
     * Create an instance of {@link InterfaceClassLib }
     * 
     */
    public InterfaceClassLib createCAEXFileInterfaceClassLib() {
        return new InterfaceClassLib();
    }

}
