//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 09:03:38 PM EEST 
//


package edu.bonn.AMLGoldStandardGenerator.aml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import edu.bonn.AMLGoldStandardGenerator.aml.CAEXFile.ExternalReference;
import edu.bonn.AMLGoldStandardGenerator.aml.CAEXFile.InstanceHierarchy;
import edu.bonn.AMLGoldStandardGenerator.aml.CAEXFile.InterfaceClassLib;
import edu.bonn.AMLGoldStandardGenerator.aml.CAEXFile.RoleClassLib;
import edu.bonn.AMLGoldStandardGenerator.aml.CAEXFile.SystemUnitClassLib;


/**
 * Root-element of the CAEX schema. 
 * 
 * <p>Java class for CAEXFile element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="CAEXFile">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;extension base="{}CAEXBasicObject">
 *         &lt;sequence>
 *           &lt;element name="ExternalReference" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{}CAEXBasicObject">
 *                   &lt;attribute name="Alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="Path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="InstanceHierarchy" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{}CAEXObject">
 *                   &lt;sequence>
 *                     &lt;element name="InternalElement" type="{}InternalElementType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="InterfaceClassLib" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{}CAEXObject">
 *                   &lt;sequence>
 *                     &lt;element name="InterfaceClass" type="{}InterfaceFamilyType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="RoleClassLib" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{}CAEXObject">
 *                   &lt;sequence>
 *                     &lt;element name="RoleClass" type="{}RoleFamilyType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="SystemUnitClassLib" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{}CAEXObject">
 *                   &lt;sequence>
 *                     &lt;element name="SystemUnitClass" type="{}SystemUnitFamilyType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;attribute name="FileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="SchemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="2.15" />
 *       &lt;/extension>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "externalReference",
    "instanceHierarchy",
    "interfaceClassLib",
    "roleClassLib",
    "systemUnitClassLib"
})
@XmlRootElement(name = "CAEXFile")
public class CAEXFile
    extends CAEXBasicObject
{

    @XmlElement(name = "ExternalReference", required = true)
    protected List<ExternalReference> externalReference;
    @XmlElement(name = "InstanceHierarchy", required = true)
    protected List<InstanceHierarchy> instanceHierarchy;
    @XmlElement(name = "InterfaceClassLib", required = true)
    protected List<InterfaceClassLib> interfaceClassLib;
    @XmlElement(name = "RoleClassLib", required = true)
    protected List<RoleClassLib> roleClassLib;
    @XmlElement(name = "SystemUnitClassLib", required = true)
    protected List<SystemUnitClassLib> systemUnitClassLib;
    @XmlAttribute(name = "FileName", required = true)
    protected String fileName;
    @XmlAttribute(name = "SchemaVersion", required = true)
    protected String schemaVersion;

    /**
     * Gets the value of the externalReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalReference }
     * 
     * 
     */
    public List<ExternalReference> getExternalReference() {
        if (externalReference == null) {
            externalReference = new ArrayList<ExternalReference>();
        }
        return this.externalReference;
    }

    /**
     * Gets the value of the instanceHierarchy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instanceHierarchy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstanceHierarchy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstanceHierarchy }
     * 
     * 
     */
    public List<InstanceHierarchy> getInstanceHierarchy() {
        if (instanceHierarchy == null) {
            instanceHierarchy = new ArrayList<InstanceHierarchy>();
        }
        return this.instanceHierarchy;
    }

    /**
     * Gets the value of the interfaceClassLib property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interfaceClassLib property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterfaceClassLib().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterfaceClassLib }
     * 
     * 
     */
    public List<InterfaceClassLib> getInterfaceClassLib() {
        if (interfaceClassLib == null) {
            interfaceClassLib = new ArrayList<InterfaceClassLib>();
        }
        return this.interfaceClassLib;
    }

    /**
     * Gets the value of the roleClassLib property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleClassLib property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleClassLib().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoleClassLib }
     * 
     * 
     */
    public List<RoleClassLib> getRoleClassLib() {
        if (roleClassLib == null) {
            roleClassLib = new ArrayList<RoleClassLib>();
        }
        return this.roleClassLib;
    }

    /**
     * Gets the value of the systemUnitClassLib property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemUnitClassLib property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemUnitClassLib().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemUnitClassLib }
     * 
     * 
     */
    public List<SystemUnitClassLib> getSystemUnitClassLib() {
        if (systemUnitClassLib == null) {
            systemUnitClassLib = new ArrayList<SystemUnitClassLib>();
        }
        return this.systemUnitClassLib;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        if (schemaVersion == null) {
            return "2.15";
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXBasicObject">
     *       &lt;attribute name="Alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ExternalReference
        extends CAEXBasicObject
    {

        @XmlAttribute(name = "Alias", required = true)
        protected String alias;
        @XmlAttribute(name = "Path", required = true)
        protected String path;

        /**
         * Gets the value of the alias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlias() {
            return alias;
        }

        /**
         * Sets the value of the alias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlias(String value) {
            this.alias = value;
        }

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXObject">
     *       &lt;sequence>
     *         &lt;element name="InternalElement" type="{}InternalElementType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "internalElement"
    })
    public static class InstanceHierarchy
        extends CAEXObject
    {

        @XmlElement(name = "InternalElement", required = true)
        protected List<InternalElementType> internalElement;

        /**
         * Gets the value of the internalElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the internalElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInternalElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InternalElementType }
         * 
         * 
         */
        public List<InternalElementType> getInternalElement() {
            if (internalElement == null) {
                internalElement = new ArrayList<InternalElementType>();
            }
            return this.internalElement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXObject">
     *       &lt;sequence>
     *         &lt;element name="InterfaceClass" type="{}InterfaceFamilyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "interfaceClass"
    })
    public static class InterfaceClassLib
        extends CAEXObject
    {

        @XmlElement(name = "InterfaceClass", required = true)
        protected List<InterfaceFamilyType> interfaceClass;

        /**
         * Gets the value of the interfaceClass property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the interfaceClass property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInterfaceClass().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InterfaceFamilyType }
         * 
         * 
         */
        public List<InterfaceFamilyType> getInterfaceClass() {
            if (interfaceClass == null) {
                interfaceClass = new ArrayList<InterfaceFamilyType>();
            }
            return this.interfaceClass;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXObject">
     *       &lt;sequence>
     *         &lt;element name="RoleClass" type="{}RoleFamilyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "roleClass"
    })
    public static class RoleClassLib
        extends CAEXObject
    {

        @XmlElement(name = "RoleClass", required = true)
        protected List<RoleFamilyType> roleClass;

        /**
         * Gets the value of the roleClass property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the roleClass property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRoleClass().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RoleFamilyType }
         * 
         * 
         */
        public List<RoleFamilyType> getRoleClass() {
            if (roleClass == null) {
                roleClass = new ArrayList<RoleFamilyType>();
            }
            return this.roleClass;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXObject">
     *       &lt;sequence>
     *         &lt;element name="SystemUnitClass" type="{}SystemUnitFamilyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "systemUnitClass"
    })
    public static class SystemUnitClassLib
        extends CAEXObject
    {

        @XmlElement(name = "SystemUnitClass", required = true)
        protected List<SystemUnitFamilyType> systemUnitClass;

        /**
         * Gets the value of the systemUnitClass property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the systemUnitClass property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSystemUnitClass().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SystemUnitFamilyType }
         * 
         * 
         */
        public List<SystemUnitFamilyType> getSystemUnitClass() {
            if (systemUnitClass == null) {
                systemUnitClass = new ArrayList<SystemUnitFamilyType>();
            }
            return this.systemUnitClass;
        }

    }

}
