//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 09:03:38 PM EEST 
//


package edu.bonn.AMLGoldStandardGenerator.aml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import edu.bonn.AMLGoldStandardGenerator.aml.InternalElementType.RoleRequirements;


/**
 * <p>Java class for InternalElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InternalElementType">
 *   &lt;complexContent>
 *     &lt;extension base="{}SystemUnitClassType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="RoleRequirements" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CAEXBasicObject">
 *                 &lt;sequence>
 *                   &lt;element name="Attribute" type="{}AttributeType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ExternalInterface" type="{}InterfaceClassType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="RefBaseRoleClassPath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MappingObject" type="{}MappingType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RefBaseSystemUnitPath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InternalElementType", propOrder = {
    "roleRequirements",
    "mappingObject"
})
public class InternalElementType
    extends SystemUnitClassType
{

    @XmlElement(name = "RoleRequirements")
    protected RoleRequirements roleRequirements;
    @XmlElement(name = "MappingObject")
    protected MappingType mappingObject;
    @XmlAttribute(name = "RefBaseSystemUnitPath")
    protected String refBaseSystemUnitPath;

    /**
     * Gets the value of the roleRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link RoleRequirements }
     *     
     */
    public RoleRequirements getRoleRequirements() {
        return roleRequirements;
    }

    /**
     * Sets the value of the roleRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleRequirements }
     *     
     */
    public void setRoleRequirements(RoleRequirements value) {
        this.roleRequirements = value;
    }

    /**
     * Gets the value of the mappingObject property.
     * 
     * @return
     *     possible object is
     *     {@link MappingType }
     *     
     */
    public MappingType getMappingObject() {
        return mappingObject;
    }

    /**
     * Sets the value of the mappingObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link MappingType }
     *     
     */
    public void setMappingObject(MappingType value) {
        this.mappingObject = value;
    }

    /**
     * Gets the value of the refBaseSystemUnitPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefBaseSystemUnitPath() {
        return refBaseSystemUnitPath;
    }

    /**
     * Sets the value of the refBaseSystemUnitPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefBaseSystemUnitPath(String value) {
        this.refBaseSystemUnitPath = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXBasicObject">
     *       &lt;sequence>
     *         &lt;element name="Attribute" type="{}AttributeType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ExternalInterface" type="{}InterfaceClassType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="RefBaseRoleClassPath" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attribute",
        "externalInterface"
    })
    public static class RoleRequirements
        extends CAEXBasicObject
    {

        @XmlElement(name = "Attribute", required = true)
        protected List<AttributeType> attribute;
        @XmlElement(name = "ExternalInterface", required = true)
        protected List<InterfaceClassType> externalInterface;
        @XmlAttribute(name = "RefBaseRoleClassPath")
        protected String refBaseRoleClassPath;

        /**
         * Gets the value of the attribute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attribute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttribute().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AttributeType }
         * 
         * 
         */
        public List<AttributeType> getAttribute() {
            if (attribute == null) {
                attribute = new ArrayList<AttributeType>();
            }
            return this.attribute;
        }

        /**
         * Gets the value of the externalInterface property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the externalInterface property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExternalInterface().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InterfaceClassType }
         * 
         * 
         */
        public List<InterfaceClassType> getExternalInterface() {
            if (externalInterface == null) {
                externalInterface = new ArrayList<InterfaceClassType>();
            }
            return this.externalInterface;
        }

        /**
         * Gets the value of the refBaseRoleClassPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefBaseRoleClassPath() {
            return refBaseRoleClassPath;
        }

        /**
         * Sets the value of the refBaseRoleClassPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefBaseRoleClassPath(String value) {
            this.refBaseRoleClassPath = value;
        }

    }

}
